name: radev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - make=4.3
  - git=2.30
  - matplotlib=3.4
  - jupyter=1.0
  - scipy=1.6
  - sphinx=4.0
  - sphinxcontrib-bibtex=2.2
  - nbsphinx=0.8
  - pandoc=2.13
  - recommonmark=0.7
  - gcc_linux-64=9.3
  - gfortran_linux-64=9.3
  - mkl=2020.4
  - fftw=3.3
  - mpich=3.4
  - funcsigs=1.0
  - vtk=9.0
